name: WorkFlow Live Server

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy the code and modify package.json and robots.txt on the DigitalOcean droplet
      - name: Deploy to DigitalOcean Droplet Live
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/hci
            echo ${{ secrets.PASSWORD }} | sudo -S git config --global --add safe.directory /var/www/html/hci
            echo ${{ secrets.PASSWORD }} | sudo -S git pull origin live
            
            # Modify the port in package.json directly on the droplet
            echo ${{ secrets.PASSWORD }} | sudo -S sed -i 's/-p 3001/-p 3002/g' package.json
            
            # Modify the robots.txt in the public folder to change Disallow rule
            echo ${{ secrets.PASSWORD }} | sudo -S sed -i 's/Disallow: \//Disallow:/' public/robots.txt

            
            cat package.json  # Verify the change in package.json
            cat public/robots.txt  # Verify the change in robots.txt

            # Install dependencies and build the app
            echo ${{ secrets.PASSWORD }} | sudo -S npm install
            echo ${{ secrets.PASSWORD }} | sudo -S npm run build

            # Restart the application using pm2
            echo ${{ secrets.PASSWORD }} | sudo -S pm2 restart all
