name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout Code
        uses: actions/checkout@v3
      # Step 2: Deploy the code to the DigitalOcean droplet via SSH (with password)
      - name: executing remote ssh commands using password Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami
