name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy the code to the DigitalOcean droplet via SSH
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.4 # Use the latest stable version
        with:
          host: ${{ secrets.SSH_HOST }} # DigitalOcean Droplet IP
          username: ${{ secrets.SSH_USERNAME }} # Your SSH username
          key: ${{ secrets.SSH_KEY }} # SSH private key stored in GitHub Secrets
          port: 22 # Default SSH port

          # Commands to run on the server
          script: |
            cd /var/www/html/website
